#workflow name
name: Pytest CI

on:
  #evenets that trigger the workflow
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
#jobs that the workflow can run
jobs:
  build-and-test:
    runs-on: ubuntu-latest
#    steps that the job contains
    steps:
      - name: ğŸ“¥ Checkout code
        uses: actions/checkout@v3

      - name: ğŸ Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: ğŸ“¦ Install dependencies (Make install)
        run: make install

      - name: ğŸ§ª Run Tests with Pytest (Make test)
        run: make test

      - name: ğŸ¨ Format Check with Black (Make format)
        run: make format

      - name: ğŸ” Lint Code with Pylint (Make lint)
        run: make lint
